name: Build-winX64Only

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
      - name: Print the changelog
        run: cat "${{ steps.git-cliff.outputs.changelog }}"
  build-windows:
    runs-on: windows-latest
    needs: changelog
    strategy:
      matrix:
        cpu: [ x64 ]
        kind: [ zip ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
      - name: Read Version Text
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
      - name: Install Pupnet
        run: |
          dotnet tool install -g KuiperZone.PupNet --version 1.7.1
      - name: Get Deps
        run: |
          .\ffmpeg.ps1 ${{ matrix.cpu }}
          .\aria2.ps1 ${{ matrix.cpu }}
        working-directory: ./script
      - name: Package
        run: |
          pupnet DownKyi.pupnet.conf --app-version ${{ steps.version.outputs.content }} --kind ${{ matrix.kind }} -r win-${{ matrix.cpu }} -y
        working-directory: ./script/pupnet
      - name: Upload build artifacts ${{ matrix.kind }}
        uses: actions/upload-artifact@v4
        with:
          name: DownKyi-${{ steps.version.outputs.content }}-1.win-${{ matrix.cpu }}.${{ matrix.kind }}
          path: script/pupnet/output/DownKyi-${{ steps.version.outputs.content }}-1.win-${{ matrix.cpu }}.${{ matrix.kind }}
      - name: Release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          allowUpdates: true
          artifacts: script/pupnet/output/DownKyi-${{ steps.version.outputs.content }}-1.win-${{ matrix.cpu }}.${{ matrix.kind }}
          body: ${{ needs.changelog.outputs.release_body }}
